import Link from "next/link"

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 page-fade">
      <article className="prose prose-invert max-w-none">
        <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: February 26, 2026</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>By accessing or using GuruBox.ai, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">2. Service Description</h2>
            <p>GuruBox.ai provides AI-powered product opportunity analysis. Each analysis generates up to 300 evaluated opportunities based on your input direction. The service is provided as-is and results are for informational purposes only.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">3. User Accounts</h2>
            <p>You must sign in with a valid Google account to use the analysis features. You are responsible for maintaining the security of your account and all activities that occur under it.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">4. Usage Limits</h2>
            <p>Each user may run one analysis at a time. We reserve the right to impose additional usage limits to ensure fair access for all users.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">5. Intellectual Property</h2>
            <p>The analysis reports generated by GuruBox.ai are provided for your personal and commercial use. However, the underlying AI models, algorithms, and platform remain the intellectual property of GuruBox.ai.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">6. Disclaimer</h2>
            <p>AI-generated analysis is based on patterns and publicly available data. GuruBox.ai does not guarantee the accuracy, completeness, or commercial viability of any opportunity identified. Users should conduct their own due diligence.</p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-foreground">7. Contact</h2>
            <p>For questions about these terms, please contact us at legal@gurubox.ai.</p>
          </section>
        </div>

        <div className="mt-8">
          <Link href="/tools/product-insight" className="text-sm text-primary underline underline-offset-4">
            Back to Home
          </Link>
        </div>
      </article>
    </div>
  )
}
